// ============================================
// 500 DAILY QUOTES — LEVEL UP / SOLO LEVELING
// One quote per day, cycled through sequentially
// ============================================

const dailyQuotes = [
    // ── DISCIPLINE & CONSISTENCY (1-100) ──
    `The difference between who you are and who you want to be is what you do today.`,
    `You do not rise to the level of your goals. You fall to the level of your systems.`,
    `A hunter does not wait for the perfect moment. A hunter creates it.`,
    `Consistency is not glamorous. But neither is regret.`,
    `The quest you skip today becomes the wall you hit tomorrow.`,
    `Discipline is choosing between what you want now and what you want most.`,
    `Every streak you protect is proof that you are becoming someone new.`,
    `Small daily improvements are the key to staggering long-term results.`,
    `The system does not reward talent. It rewards those who show up.`,
    `You are not behind. You are building. Keep going.`,
    `One percent better every day. That is the only algorithm that matters.`,
    `The pain of discipline weighs ounces. The pain of regret weighs tons.`,
    `Your habits are silently voting for the person you are becoming.`,
    `Champions are not made in the arena. They are made in the hours nobody sees.`,
    `A day without progress is a day the old version of you wins.`,
    `Motivation fades. Rituals remain. Build your rituals.`,
    `The hunter who trains every day will always outclass the one who trains when inspired.`,
    `Repetition is not boring. Repetition is how legends are forged.`,
    `You will never regret showing up. You will always regret giving in.`,
    `The hardest quest is the one you start. The rest is momentum.`,
    `What you do on the days you do not feel like it defines who you become.`,
    `Consistency does not mean perfection. It means never quitting.`,
    `The compound effect is invisible until it is undeniable.`,
    `Your future self is watching you right now through your habits.`,
    `Every completed quest is a brick in the foundation of who you are building.`,
    `Do not count the days. Make the days count.`,
    `The gap between where you are and where you want to be is filled with daily action.`,
    `Intensity impresses. Consistency transforms.`,
    `A missed day is not failure. A missed week is a choice.`,
    `The system rewards patience. Keep leveling.`,
    `Success is rented. The rent is due every single day.`,
    `You do not need a new strategy. You need to execute the one you have.`,
    `The quest is simple. Show up. Do the work. Repeat.`,
    `Ordinary effort over extraordinary time creates extraordinary results.`,
    `Your streak is not a number. It is a statement about who you are.`,
    `The days you do not want to train are the days that matter most.`,
    `If it were easy, everyone would be leveled up. It is not. That is why it matters.`,
    `Progress requires no permission. Only action.`,
    `The most powerful force in personal growth is showing up again tomorrow.`,
    `You are one habit away from a completely different life.`,
    `Mastery is not about doing extraordinary things. It is about doing ordinary things extraordinarily well.`,
    `A hunter who rests too long becomes prey.`,
    `Do not break the chain. The chain is building something you cannot yet see.`,
    `When the quest feels impossible, remember why you started.`,
    `Your potential has an expiry date. It is called inaction.`,
    `The best time to level up was yesterday. The second best time is right now.`,
    `Commitment means staying loyal to what you said you would do long after the mood has left you.`,
    `Every day is a boss fight. The boss is the version of you that wants to quit.`,
    `If you are tired of starting over, stop giving up.`,
    `The system does not care about your excuses. It cares about your effort.`,
    `Fall seven times. Rise eight. That is the way of the hunter.`,
    `A strong start means nothing without a strong finish. Stay locked in.`,
    `The only workout you regret is the one you did not do. Same applies to your quests.`,
    `Stop waiting for the right time. The right time is the time you decide to start.`,
    `Results happen over time, not overnight. Work hard, stay consistent, and be patient.`,
    `There is no elevator to the top. You have to take the stairs. One quest at a time.`,
    `The secret to getting ahead is getting started.`,
    `Discipline is the bridge between your goals and your accomplishments.`,
    `Your daily routine is your daily vote for the life you want.`,
    `Hard choices, easy life. Easy choices, hard life.`,
    `The grind is not punishment. The grind is the price of entry.`,
    `You cannot cheat the grind. It knows how much you have invested. It will not give you anything you have not worked for.`,
    `When you feel like quitting, remember why you started this journey.`,
    `The distance between your dreams and reality is called discipline.`,
    `A hunter who only trains in good weather will fall in the first storm.`,
    `The habits you build today are the results you see tomorrow.`,
    `Excuses will always be there for you. Opportunity will not.`,
    `Today is the tomorrow you talked about yesterday. Make it count.`,
    `Your comfort zone is a beautiful place but nothing grows there.`,
    `It is not about having time. It is about making time.`,
    `Stop wishing. Start doing. The system is watching.`,
    `The only person you are competing with is the person you were yesterday.`,
    `Winners are not people who never fail. They are people who never quit.`,
    `Greatness is a lot of small things done well, day after day.`,
    `You do not have to be extreme. Just be consistent.`,
    `When you want to quit, think about why you started.`,
    `The magic you are looking for is in the work you are avoiding.`,
    `Motivation is what gets you started. Habit is what keeps you going.`,
    `Sacrifice is not losing something. It is exchanging something for something greater.`,
    `Every master was once a disaster. Keep training.`,
    `There are no shortcuts to any place worth going.`,
    `The successful hunter is the average hunter who did not give up.`,
    `Goals without daily action are just wishes.`,
    `Be stubborn about your goals and flexible about your methods.`,
    `The cost of not pursuing your goals is greater than the cost of pursuing them.`,
    `It always seems impossible until it is done.`,
    `Do what is hard now so your future self can live what is easy.`,
    `What seems like overnight success usually takes years of grinding. Keep going.`,
    `You are stronger than your excuses.`,
    `Arise. Not because it is easy. Because it is necessary.`,
    `A strong mind builds a strong life. Train both.`,
    `You are the author of your story. Write something legendary.`,
    `Comfort is the enemy of growth. Get uncomfortable today.`,
    `An S-rank hunter was once an E-rank who refused to quit.`,
    `You have survived every bad day so far. Your record is undefeated.`,
    `Stop overthinking. Start overdelivering.`,
    `Progress is not always visible. But it is always happening when you show up.`,
    `The system is simple. Do the work. Trust the process. Level up.`,
    `You did not come this far to only come this far.`,
    `Be so disciplined that the old version of you would not recognize you.`,
    `The hunt never stops. Neither should your effort.`,

    // ── GROWTH & SELF-IMPROVEMENT (101-200) ──
    `Growth is painful. Change is painful. But nothing is as painful as staying stuck.`,
    `You cannot become a new person by continuing to be the old one.`,
    `The version of you that exists six months from now is being built by what you do today.`,
    `A caterpillar has to completely dissolve before it becomes a butterfly. Growth is messy. Trust it.`,
    `Invest in yourself. It pays the best interest.`,
    `The most dangerous thing you can do is stay the same when the world is changing around you.`,
    `Growth means being willing to look foolish while you learn.`,
    `The only way to grow is to step into the unknown repeatedly.`,
    `You were not born to be perfect. You were born to be real, to evolve, to level up.`,
    `If you are the smartest person in the room, you are in the wrong room.`,
    `Learning is a treasure that will follow you everywhere.`,
    `The moment you stop learning, you start dying.`,
    `Be a student. Stay open. Stay hungry. The world has endless quests.`,
    `Growth is not about adding more. Sometimes it is about removing what no longer serves you.`,
    `Your biggest competition is the person staring back at you in the mirror.`,
    `Yesterday's level is not enough for today's boss fight.`,
    `Every setback is a setup for a comeback if you let it teach you.`,
    `The person who reads is the person who leads. Feed your mind.`,
    `You evolve by facing challenges, not avoiding them.`,
    `Strength does not come from what you can do. It comes from overcoming the things you once thought you could not.`,
    `Growth lives on the other side of fear.`,
    `A seed has to break before it becomes a tree. You are not breaking. You are becoming.`,
    `Outgrow yourself. That is the quest.`,
    `Your potential is not a fixed stat. It levels up when you do.`,
    `The discomfort you feel right now is growth knocking on your door. Let it in.`,
    `Be addicted to bettering yourself.`,
    `Old keys will not open new doors. Evolve your approach.`,
    `You are not too old to level up. You are not too late. You are right on time.`,
    `Improvement starts when you stop making excuses.`,
    `Level up your mind and everything else will follow.`,
    `The only limit to your growth is the limit you accept.`,
    `Transformation does not ask for permission. It demands action.`,
    `Today you are the weakest version of your future self. That should excite you.`,
    `Growth requires sacrifice. What are you willing to give up to level up?`,
    `The best project you will ever work on is you.`,
    `Do not wish it were easier. Wish you were better. Then become it.`,
    `Self-improvement is not selfish. It is necessary.`,
    `You cannot pour from an empty cup. Level yourself up first.`,
    `Become the person who attracts the results you want.`,
    `The mind is a muscle. Train it or it will atrophy.`,
    `Knowledge without action is just entertainment. Apply what you learn.`,
    `Every hunter who leveled up once felt exactly like you do right now. Keep going.`,
    `Your current situation is not your final destination.`,
    `Growth happens at the edge of your ability. Push the edge.`,
    `The strongest steel is forged in the hottest fire. Embrace the heat.`,
    `You are a work in progress. And that is okay. Progress is the point.`,
    `It is never too late to become who you were meant to be.`,
    `Doubt kills more dreams than failure ever will.`,
    `The only impossible journey is the one you never begin.`,
    `What you think, you become. What you feel, you attract. What you imagine, you create.`,

    // ── MENTAL STRENGTH & RESILIENCE (151-250) ──
    `A calm mind is an unstoppable mind.`,
    `Pressure does not break a hunter. It reveals one.`,
    `The battle is won or lost in your mind long before it is fought in reality.`,
    `You cannot control what happens to you. You can control how you respond.`,
    `Tough times do not last. Tough hunters do.`,
    `Fear is not the enemy. Hesitation is.`,
    `Failure is not falling down. Failure is refusing to get back up.`,
    `Pain is temporary. The pride of accomplishment lasts forever.`,
    `The mind will always quit before the body. Train your mind first.`,
    `Every obstacle is a training arc in disguise.`,
    `Be water. Flow around obstacles. Do not let them stop you.`,
    `It is okay to have bad days. It is not okay to let bad days define you.`,
    `Stress is caused by being here but wanting to be there. Be here. Fully.`,
    `Mental toughness is not about ignoring your pain. It is about choosing to move through it.`,
    `Adversity introduces you to yourself. What will you discover?`,
    `A strong mind can carry a tired body. A weak mind will abandon a strong one.`,
    `Embrace the struggle. It is crafting you into someone unshakable.`,
    `The obstacle is not in your way. It is your way.`,
    `Do not pray for an easy life. Pray for the strength to endure a difficult one.`,
    `You have been through worse and you survived. You will survive this too.`,
    `Resilience is not about never falling. It is about how fast you rise again.`,
    `The voice in your head that says you cannot do it is a liar. Prove it wrong.`,
    `Every dungeon has an exit. Keep fighting until you find it.`,
    `Your setbacks are setups. Your losses are lessons. Your pain is progress.`,
    `When everything seems to be going against you, remember that an airplane takes off against the wind, not with it.`,
    `Patience is not the ability to wait. It is the ability to keep a good attitude while working hard.`,
    `The comeback is always stronger than the setback.`,
    `You are not stuck. You are just preparing for your next breakthrough.`,
    `A warrior does not give up what they want most for what they want right now.`,
    `There is no growth in comfort and no comfort in growth. Choose growth.`,
    `The moment you accept total responsibility for everything in your life is the moment you claim the power to change it.`,
    `Rock bottom has built more champions than privilege ever has.`,
    `Life does not get easier. You get stronger. That is the point.`,
    `Protect your peace but never stop chasing your potential.`,
    `You will never be truly ready. Start anyway.`,
    `The weight on your shoulders today is building the strength you need for tomorrow.`,
    `Silence the doubt. Amplify the work.`,
    `Warriors are not born. They are forged through trials they refused to run from.`,
    `The strongest people are not those who show strength in front of us. They are those who win battles we know nothing about.`,
    `Your struggles are developing your strengths. Do not give up.`,
    `Not every day will be good. But there is something good in every day.`,
    `Overthinking will destroy your happiness and your progress. Just do the next thing.`,
    `The only walls that exist are the ones you place in your own mind.`,
    `You have already made it through days you thought would break you. You are tougher than you think.`,
    `It is not about being fearless. It is about acting despite the fear.`,
    `What consumes your mind controls your life. Choose your thoughts carefully.`,
    `Hardship often prepares ordinary people for extraordinary things.`,
    `The fire that burns inside you is stronger than the storm around you.`,
    `Do not shrink yourself to fit into spaces you have outgrown.`,
    `You did not fail. You found a strategy that does not work. Adjust and continue.`,

    // ── ACTION & EXECUTION (201-300) ──
    `Thinking will not overcome fear. Action will.`,
    `Ideas are worthless without execution. Execute today.`,
    `A plan without action is just a dream. A dream without action is just a wish.`,
    `Stop planning your life and start living it.`,
    `Done is better than perfect. Ship it.`,
    `The world does not pay you for what you know. It pays you for what you do.`,
    `Massive action cures everything.`,
    `Do not wait for opportunities. Create them.`,
    `Action exposes what hesitation hides.`,
    `The hunter who moves first controls the fight.`,
    `Ready is a myth. Start before you are ready.`,
    `If you spend too long holding on to the one who treats you like an option, you will miss finding the one who treats you like a priority. Same with goals.`,
    `Speed of implementation is the greatest competitive advantage.`,
    `Talk less. Build more. The results will speak for themselves.`,
    `Every action you take is a vote for the person you wish to become.`,
    `You miss one hundred percent of the shots you do not take.`,
    `The difference between a master and a beginner is that the master has failed more times than the beginner has tried.`,
    `Execution separates dreamers from achievers.`,
    `Stop announcing your moves. Just make them.`,
    `You do not have to see the whole staircase. Just take the first step.`,
    `While you are waiting for the perfect time, someone else is already doing it imperfectly and winning.`,
    `Action is the antidote to despair.`,
    `You know what you need to do. Stop looking for confirmation. Do it.`,
    `Less thinking. More doing. That is the formula.`,
    `Start messy. Start ugly. Just start.`,
    `The cost of inaction is far greater than the cost of making a mistake.`,
    `A good plan executed now is better than a perfect plan executed next week.`,
    `Stop being a spectator in your own life. Get in the game.`,
    `The only thing standing between you and your goal is the story you keep telling yourself about why you cannot achieve it.`,
    `Every morning you have two choices: continue to sleep with your dreams, or wake up and chase them.`,
    `If you want something you have never had, you must be willing to do something you have never done.`,
    `Your life changes the moment you make a new, congruent, and committed decision.`,
    `The path to success is to take massive, determined action.`,
    `Clarity comes from engagement, not thought. Act first.`,
    `You are only one decision away from a totally different life.`,
    `Do not let what you cannot do interfere with what you can do.`,
    `The graveyard is full of unfulfilled potential. Do not add to it.`,
    `Stop waiting to be picked. Pick yourself.`,
    `First they will ask why you are doing it. Later they will ask how you did it.`,
    `Work in silence. Let your level speak.`,
    `The hunter who hesitates gets left behind.`,
    `You cannot steer a parked car. Get moving first, then adjust direction.`,
    `Nothing changes if nothing changes. Make a move.`,
    `Doubt is a signal to act, not a signal to stop.`,
    `Build now. Optimize later. The perfect system does not exist yet.`,
    `Action breeds confidence. Inaction breeds doubt.`,
    `Your to-do list will not complete itself. Arise.`,
    `The best things in life are on the other side of doing things you do not want to do.`,
    `Do not tell people about your plans. Show them your results.`,
    `Every big achievement started with someone deciding to try.`,

    // ── PURPOSE & VISION (251-350) ──
    `Know your why and the how becomes easier.`,
    `A life without purpose is a life without direction. Find your quest.`,
    `Purpose is not found. It is built through action and reflection.`,
    `The hunter who knows why can endure any how.`,
    `Vision without execution is hallucination. Execute daily.`,
    `Your purpose is not to be comfortable. Your purpose is to grow.`,
    `When you are clear on what you want, the universe steps aside.`,
    `Stop chasing success. Chase purpose. Success will follow.`,
    `Clarity of vision creates clarity of action.`,
    `Live with intention. Everything else is just existing.`,
    `Your life purpose is under construction. Keep building.`,
    `Passion fades. Purpose endures. Build on purpose.`,
    `The person without a goal is forever working for the person who has one.`,
    `Direction is more important than speed. Many are going nowhere fast.`,
    `You are not lost. You are exploring. The quest has not ended.`,
    `A ship without a destination drifts. Set your coordinates.`,
    `Do not just exist. Live with fire. Live with meaning.`,
    `The meaning of life is to find your gift. The purpose of life is to give it away.`,
    `Ambition without direction is chaos. Direct your energy.`,
    `Your mission is too important to be sidetracked by mediocrity.`,
    `Create the life you cannot wait to wake up to.`,
    `When your purpose is clear, your decisions become simple.`,
    `A hunter without a mission is just wandering the map.`,
    `Stop surviving. Start living with intention.`,
    `Align your daily actions with your deepest values.`,
    `The best way to predict the future is to create it.`,
    `Legacy is not about what you accumulate. It is about what you build.`,
    `Make your life a story worth telling.`,
    `Purpose gives ordinary days extraordinary meaning.`,
    `Focused energy is the most powerful force in the universe.`,
    `The two most important days in your life are the day you are born and the day you find out why.`,
    `Chase the vision, not the money. The money will follow the vision.`,
    `If your dreams do not scare you, they are not big enough.`,
    `The hunter who chases two rabbits catches neither. Focus.`,
    `Build a life that does not need a vacation from.`,
    `Your north star is not someone else's achievement. Find your own.`,
    `A life lived for others is a life worthwhile.`,
    `Impact over income. Purpose over profit. Always.`,
    `Decide what you want. Write it down. Work on it every single day.`,
    `The biggest adventure you can take is to live the life of your dreams.`,
    `You are here for a reason. Act like it.`,
    `Dream so big that people think you are crazy. Then prove them wrong.`,
    `Your time is limited. Do not waste it living someone else's life.`,
    `Make yourself proud. That is the real quest.`,
    `Purpose fuels perseverance when motivation runs dry.`,
    `Be so focused on your vision that distractions become invisible.`,
    `The world needs what you have to offer. Stop hiding.`,
    `Leave every room better than you found it. That is the real level up.`,
    `Build something that outlasts you.`,
    `Your legacy is every life you touch. Make it matter.`,

    // ── LEVEL UP THEMED (351-500) ──
    `The system window just appeared. Your quest for today is ready. Will you accept it?`,
    `Arise. The dungeon gates will not wait forever.`,
    `Your daily quests are not obstacles. They are XP waiting to be claimed.`,
    `In this life, there are no NPCs. Everyone is the main character of their story. Play yours well.`,
    `The difference between an E-rank and an S-rank is the number of quests they refused to skip.`,
    `Every dungeon you clear today makes tomorrow's dungeon easier.`,
    `Your stats do not lie. They reflect exactly how much work you have put in.`,
    `The system does not give you quests you cannot handle. Trust the process.`,
    `A true hunter does not compare their level to others. They compare it to who they were yesterday.`,
    `The penalty for an incomplete quest is not punishment. It is stagnation. And stagnation is death.`,
    `Shadows are not born. They are earned through relentless effort.`,
    `The strongest hunters in this server were once where you are right now. Keep grinding.`,
    `Think of every habit as a skill tree. Every day you practice, you unlock a new node.`,
    `Your character build is entirely up to you. Allocate your stats wisely today.`,
    `The respawn point is right here. Right now. Every morning is a new life.`,
    `Boss fights are not meant to be easy. They are meant to evolve you. Welcome the challenge.`,
    `If life is a dungeon, then your habits are your equipment. Upgrade them daily.`,
    `Do not grind for rewards. Grind for who you become during the grind.`,
    `An unfinished quest list at the end of the day is an honest mirror. What does yours reflect?`,
    `You are not starting from scratch. You are starting from experience. There is a difference.`,
    `Your level does not define your worth. Your willingness to keep leveling does.`,
    `The system notification you need today: you are capable of more than you believe.`,
    `Every streak is a chain of proof that the new version of you is real.`,
    `The raid is not over. Your party is counting on you. Show up.`,
    `Some days the XP feels small. But small XP over a year creates a monster. Keep stacking.`,
    `A hunter's greatest weapon is not strength. It is consistency.`,
    `The daily quest seems simple until you try to do it for three hundred sixty five days straight. That is where legends are born.`,
    `Your inventory is full of potential. Time to equip it and use it.`,
    `The gate just opened. Will you walk through it or wait for someone else to clear the path?`,
    `You do not need to be the strongest hunter in the room. You just need to be stronger than you were yesterday.`,
    `The grind never promised to be fun. It promised to be worth it. Trust the grind.`,
    `Every time you open the app and complete a quest, you are telling the universe you are serious.`,
    `The leaderboard does not care about talent. It cares about reps. Put in the reps.`,
    `Solo leveling is not about being alone. It is about being accountable to yourself first.`,
    `Your quest log does not fill itself. Neither does your potential. Both require daily attention.`,
    `The shadow army was not built in a day. Neither is the best version of you.`,
    `Stop waiting for a party invite. Solo the dungeon. You are stronger than you think.`,
    `The only cheat code in life is discipline applied relentlessly.`,
    `Your power level is a reflection of your daily habits. What are you training today?`,
    `The system does not reward wishful thinking. It rewards completed quests.`,
    `A hunter who avoids the dungeon never discovers what they are truly capable of.`,
    `The quest that scares you most is usually the one that will level you up the fastest.`,
    `You have been dormant long enough. It is time to awaken. Arise.`,
    `The XP bar does not fill itself. Every action you take today adds to it.`,
    `This is not a game. This is your life. Play it like it matters. Because it does.`,
    `The weakest hunter in the dungeon is the one who never entered. Be brave enough to enter.`,
    `Stats are earned, not given. Your effort today determines your stats tomorrow.`,
    `Treat every challenge like a dungeon boss. Study it. Prepare. Then execute.`,
    `The system chose you for a reason. Do not waste the opportunity.`,
    `Every morning the system resets. Fresh quests. Fresh XP. Fresh chances. Do not squander them.`,
    `Your character arc is not written by fate. It is written by the choices you make every single day.`,
    `The most dangerous hunter is not the one with the highest level. It is the one who never stops grinding.`,
    `There are no save points in real life. Every day counts. Make today legendary.`,
    `A true hunter measures progress not by the rank they hold but by the person they have become.`,
    `The guild is stronger when every hunter shows up. You are part of this guild. Show up today.`,
    `The notification just dropped. Your daily quests are live. Will you answer the call?`,
    `Think of discipline as your base stat. Everything else scales from it.`,
    `In the world of Level Up, there are no lucky drops. There is only earned loot. Go earn yours.`,
    `You are one completed quest away from building unstoppable momentum.`,
    `Hunters do not make excuses. They make progress.`,
    `The training arc is the most boring part of every story. But it is also the most important. You are in your training arc.`,
    `Logging your quests is not a task. It is a declaration that today mattered.`,
    `Every habit you build is a permanent buff that stacks over time.`,
    `The dungeon does not get easier. You get stronger. That is the system working.`,
    `Your streak is not just a number on a screen. It is a reflection of your character.`,
    `A missed quest is not the end. But a pattern of missed quests is a choice to stay the same.`,
    `The hunters who inspire you were once exactly where you are. The only difference is they did not stop.`,
    `Level one is not a weakness. It is a beginning. And every legend has a beginning.`,
    `The system is fair. It gives back exactly what you put in. Nothing more. Nothing less.`,
    `Arise, hunter. Not tomorrow. Not next week. Now.`,
    `Your potential is an unexplored dungeon. You will never know how deep it goes unless you enter.`,
    `When the quest feels pointless, remember that the XP always compounds.`,
    `Even the Monarch started as a solo hunter in an empty dungeon. Your beginning does not define your end.`,
    `The app is a mirror. It reflects your discipline back to you. What does it show today?`,
    `Stop spectating. Start playing. Your quests are waiting.`,
    `The hunters who level up fastest are not the most talented. They are the most consistent.`,
    `In the end, your level will tell the story of every quest you completed and every day you showed up.`,
    `There is no final boss. There is only the next version of you to defeat. Keep leveling. Always.`,
    `Today's quest might seem small. But stacked with yesterday's and tomorrow's, it becomes unstoppable.`,
    `The system has given you another day. That is not a coincidence. That is an opportunity. Use it.`,
    `A hunter's journal tells the truth. Open the app. Write today's chapter.`,
    `Somewhere out there, a hunter with less resources than you is outworking you because they decided to stop making excuses.`,
    `The dungeon gate is open. The quest is set. The only question left is: will you arise?`,
    `You were not given this life to watch from the sidelines. You were given this life to level up. So level up.`,
    `Every single day is a new chance to rewrite your stats. Make today's numbers better than yesterday's.`,
    `The strongest armor a hunter can wear is discipline. It deflects doubt, fear, and laziness.`,
    `Your story is still being written. Make sure today's chapter is one worth reading.`,
    `The quest board is full. Your potential is limitless. The only bottleneck is your willingness to begin.`,
    `Arise and grind. Not for anyone else. For the version of you that is waiting on the other side of the effort.`,
    `This is your system. This is your journey. No one else can complete your quests for you. Own it.`,
    `A hundred days from now you will wish you had started today. So start today.`,
    `The system does not hand out free levels. But it does reward every single effort. No matter how small.`,
    `The difference between a hunter and everyone else is simple: the hunter chose to begin. Choose to begin.`,
    `The grind is lonely sometimes. But so is greatness. Keep going.`,
    `Your level is not your limit. It is your launchpad.`,
    `Arise, hunter. The world is waiting for the version of you that refuses to quit.`,

    // ── BONUS QUOTES (398-500) ──
    `Clarity comes from action, not thought. Move first. Adjust later.`,
    `The person who moves mountains begins by carrying small stones.`,
    `You are not defined by what happened to you. You are defined by what you do next.`,
    `A hunter's strength is measured not by their power but by what they overcame to get it.`,
    `Stop romanticizing the grind and start doing it. Action beats aesthetics.`,
    `The world will never see the hours you put in. But your results will speak for them.`,
    `Rest when you must. But never quit while you are still capable of another step.`,
    `Distractions are just dungeons with no rewards. Avoid them.`,
    `Every morning is a respawn. Play this life like it is your last.`,
    `The system does not grade on a curve. It measures raw effort. Put in the work.`,
    `Your environment shapes your habits. Design an environment that builds the person you want to be.`,
    `The easiest path leads to the hardest life. Choose the hard path now.`,
    `A hunter without enemies has never stood for anything. Stand for your growth.`,
    `Do not wait for the storm to pass. Learn to fight in the rain.`,
    `Procrastination is the thief of levels. Do not let it rob you.`,
    `Your reputation is what others think of you. Your character is what you do when nobody is watching.`,
    `The most important conversation you will ever have is the one you have with yourself. Make it empowering.`,
    `Be the kind of person that when you wake up, mediocrity shakes.`,
    `Time is the most valuable currency. Spend it on things that compound.`,
    `Pain today. Strength tomorrow. That is the trade. Take it.`,
    `The hunters who stand at the top did not get there by sitting down.`,
    `Your energy flows where your attention goes. Focus on what builds you.`,
    `Replace I should with I will and watch your life change.`,
    `Talent sets the floor. Work ethic sets the ceiling. Raise your ceiling.`,
    `An hour of focused work beats a day of distracted effort. Focus is the multiplier.`,
    `The strongest version of you does not exist yet. Build them one day at a time.`,
    `Comfort will whisper. Ambition will roar. Listen to the roar.`,
    `What you tolerate is what you accept. Raise your standards today.`,
    `A one percent improvement daily leads to a thirty-seven times improvement in a year.`,
    `The grind does not have a finish line. That is the beauty of it.`,
    `Stop looking for a mentor. Become the person your future self needed.`,
    `Showing up when it is hard is worth ten times more than showing up when it is easy.`,
    `The gap between I want to and I am going to is called a decision. Decide.`,
    `Your daily choices are either building your dream or building someone else's. Choose wisely.`,
    `Champions adjust. They do not abandon. When something is not working, pivot. Do not quit.`,
    `Every expert was once a beginner. Every pro was once an amateur. Keep going.`,
    `A sharp mind and a strong body are the ultimate combination. Train both daily.`,
    `You are the CEO of your life. Start making executive decisions.`,
    `Silence is the best response to a fool. Progress is the best response to a critic.`,
    `Energy is renewable. Time is not. Spend your time on things that matter.`,
    `The path forward is not always clear. Walk anyway. Clarity comes with movement.`,
    `What you allow is what will continue. Stop allowing mediocrity.`,
    `The hunter who controls their morning controls their day. Control your morning.`,
    `Speed is not the goal. Direction is. Make sure you are heading somewhere meaningful.`,
    `Perfection is the enemy of progress. Launch ugly. Iterate later.`,
    `Your network is your net worth. Surround yourself with hunters who elevate you.`,
    `The only approval you need is from the person you will be in five years.`,
    `Bet on yourself. You are the safest investment you will ever make.`,
    `A day wasted is a day the competition gained on you. Make every day intentional.`,
    `If the plan does not work, change the plan. Never change the goal.`,
    `The river that carves the deepest canyon is the one that never stops flowing. Be that river.`,
    `Read more. Scroll less. Your mind is a garden. Feed it quality seeds.`,
    `The harder the battle, the sweeter the victory. Embrace the hard.`,
    `Do not be afraid of moving slowly. Be afraid of standing still.`,
    `You cannot go back and change the beginning. But you can start where you are and change the ending.`,
    `The most successful people in the world were told they would fail. They did not listen. Neither should you.`,
    `Every day you delay is a day of growth you will never get back.`,
    `The hunter who walks alone often walks the fastest. But the guild walks the farthest. Balance both.`,
    `Invest your time before you spend it. Planning is the ultimate cheat code.`,
    `Gratitude multiplies what you have. Complaining multiplies what you lack. Choose gratitude.`,
    `Make your actions match your ambitions. Anything less is self-sabotage.`,
    `Your phone is either a tool or a trap. Decide which one it is today.`,
    `Sleep is not laziness. It is recovery. Rest strategically so you can grind sustainably.`,
    `Anger at your situation is fuel. Channel it into effort, not excuses.`,
    `The best revenge is massive success. Go get yours.`,
    `Write down your goals. The ones who write them down are ten times more likely to achieve them.`,
    `Comparison is a dungeon with no exit. Stay out of it. Run your own race.`,
    `Your past is a lesson, not a life sentence. Learn from it and move forward.`,
    `Every skill you learn is a permanent buff. Stack skills relentlessly.`,
    `Boredom is a sign that you are not challenging yourself enough. Raise the difficulty.`,
    `The world breaks everyone, and afterward, many are strong at the broken places.`,
    `You are allowed to be a masterpiece and a work in progress simultaneously.`,
    `Fall in love with the process and the results will follow.`,
    `Focus on systems, not goals. Goals tell you where to go. Systems get you there.`,
    `The most disciplined person in the room is usually the most free. Discipline equals freedom.`,
    `Train yourself to start. Starting is the hardest part. Everything after that is momentum.`,
    `You have the same twenty-four hours as everyone else. It is not about time. It is about priorities.`,
    `Comfort zones are where dreams go to die. Step out. Stay out.`,
    `What you repeatedly do becomes who you permanently are. Choose your repetitions wisely.`,
    `The obstacle you are avoiding is exactly the one you need to face.`,
    `Winners focus on winning. Losers focus on winners. Focus on your own game.`,
    `Be patient with results but impatient with actions. Move fast. Wait patiently.`,
    `The best investment you can make is in your own ability. Never stop learning.`,
    `Sometimes the bravest thing you can do is keep going when everything says stop.`,
    `Your future is created by what you do today, not tomorrow.`,
    `The grind does not care about your mood. Show up regardless.`,
    `Do not let the noise of others' opinions drown out your own inner voice.`,
    `A diamond is just a chunk of coal that handled stress exceptionally well.`,
    `The best time to plant a tree was twenty years ago. The second best time is now.`,
    `Life is a solo leveling experience. Nobody else can earn your XP for you.`,
    `Embrace the suck. The parts that feel terrible are usually the parts that change you the most.`,
    `The market always pays for value. Become valuable.`,
    `You will not always be motivated. You will not always be inspired. Show up anyway.`,
    `A quitter never wins and a winner never quits. Simple truth.`,
    `Your word is your bond. When you say you will do something, do it. Especially to yourself.`,
    `Do not let yesterday take up too much of today.`,
    `Every next level of your life will demand a different version of you.`,
    `The pain you feel today is the strength you feel tomorrow.`,
    `You are not lazy. You are just uninspired. Find your mission and watch everything change.`,
    `Stay hungry. Stay foolish. Stay disciplined. The world is yours.`,
    `Fear kills more dreams than failure ever will. Do it scared.`,
    `Arise. Not for applause. Not for validation. For the version of you that is waiting to be built.`,
    `The system is always live. The quest board is always full. The choice to begin is always yours.`,
    `Today is not just another day. It is another chance. Another quest. Another opportunity to level up. Take it.`,
];

module.exports = dailyQuotes;

